pipeline {
    agent any

    environment {
        NEXUS_CREDENTIALS_ID = 'nexus-id' // ID of your stored Nexus credentials
        NEXUS_URL = 'nexus:8081' // Replace with your Nexus URL
        REPO_NAME = 'maven-snapshots' // Replace with your Nexus repository name
    }

    tools {
            // Specify the Gradle version configured in Jenkins
            gradle 'gradle'
        }
options {
    gitLabConnection('GitLabStud')
}
    stages {
        stage('Clean Workspace') {
            steps {
                echo 'test'
                updateGitlabCommitStatus name: 'build', state: 'pending'
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('hello-world'){
                sh './gradlew build'
                }

            }
        }

        stage('Test') {
            steps {
                dir('hello-world'){
                sh './gradlew test'
                }

            }
        }

        stage('Upload to Nexus') {
            steps {
                dir('hello-world/build/libs'){
                script {
                    // Upload the JAR file to Nexus
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: NEXUS_URL,
                        groupId: 'com.example',
                        version: '0.0.1-SNAPSHOT',
                        repository: REPO_NAME,
                        credentialsId: NEXUS_CREDENTIALS_ID,
                        artifacts: [
                            [artifactId: 'myapp',
                            classifier: '',
                            file: 'hello-world-0.0.1-SNAPSHOT.jar',
                            type: 'jar']
                        ]
                    )
                }

                }

            }
        }
    }
    post {
       success {
           updateGitlabCommitStatus name: 'build', state: 'success'
       }

       failure {

            updateGitlabCommitStatus name: 'build', state: 'failed'
        }
   }
}